{
 "title": "阿里云网络监控Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "云企业网区域间带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "application": { "filter": "aliyun_network" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "ZabbixServer" },
     "item": { "filter": "/.*区域间带宽$/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "云企业网区域间带宽百分比",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "aliyun_network" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "ZabbixServer" },
     "item": { "filter": "/.*区域间带宽百分比.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "公网IP流出带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "application": { "filter": "aliyun_network" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "ZabbixServer" },
     "item": { "filter": "/.*流出带宽.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "公网IP流入带宽展示",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "application": { "filter": "aliyun_network" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "ZabbixServer" },
     "item": { "filter": "/.*流入带宽.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "公网IP丢包率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "aliyun_network" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "ZabbixServer" },
     "item": { "filter": "/.*丢包率检测.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "公网IP网络带宽值",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "application": { "filter": "aliyun_network" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "ZabbixServer" },
     "item": { "filter": "/阿里云产品: .*网络总带宽大小/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "每秒7层协议端口5XX状态",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "aliyun_network" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "ZabbixServer" },
     "item": { "filter": "/.*每秒7层协议端口5XX状态.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "每秒端口并发连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "aliyun_network" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "ZabbixServer" },
     "item": { "filter": "/.*每秒端口并发连接数.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "最大连接数使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "application": { "filter": "aliyun_network" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "ZabbixServer" },
     "item": { "filter": "/.*最大连接数使用率.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "云企业网地域间限速丢包速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "aliyun_network" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "ZabbixServer" },
     "item": { "filter": "/.*cen.*限速丢包速率.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}