{
 "title": "Kubernetes JMX Dashboard",
 "description": "JMX Dashboard for Kubernetes Monitoring with Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "application", "query": "label_values(jvm_info,service)" },
   {
    "name": "instance",
    "query": "label_values(jvm_info{service=\"$application\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{service=\"$application\",pod=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{service=\"$application\",pod=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_start_time_seconds{service=\"$application\",pod=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "label_join(jvm_info{service=\"$application\",pod=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "JVM Memory Area (Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{service=\"$application\",pod=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_committed{service=\"$application\",pod=\"$instance\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": " jvm_memory_bytes_max{service=\"$application\",pod=\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{service=\"$application\",pod=\"$instance\"}/jvm_memory_bytes_max{service=\"$application\",pod=\"$instance\"}",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "JVM Memory Area (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{service=\"$application\",pod=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_committed{service=\"$application\",pod=\"$instance\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pod=\"$pod\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod=\"$instance\"}",
     "legendFormat": "Current"
    },
    {
     "expr": " jvm_threads_daemon{pod=\"$instance\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": " jvm_threads_peak{pod=\"$instance\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": " jvm_threads_deadlocked{pod=\"$instance\"}",
     "legendFormat": "Deadlocked"
    }
   ]
  },
  {
   "title": "JVM Class Loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{pod=\"$instance\"}",
     "legendFormat": "Loaded"
    },
    {
     "expr": " jvm_classes_loaded_total{pod=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "JVM GC Time [3m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{pod=\"$instance\"}[3m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM GC Count Increase [3m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{pod=\"$instance\"}[3m])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}