{
 "title": "微服务监控",
 "description": "JMX exporter dashboard for metrics exported by Prometheus Operator",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(jvm_info, namespace)"
   },
   {
    "name": "service",
    "query": "label_values(jvm_info{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(jvm_info{namespace=\"$namespace\", service=\"$service\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_join(jvm_info{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "实例数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$service\",namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "所有实例CPU cores使用",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$service\"}[5m]))",
     "legendFormat": "current"
    },
    {
     "expr": "sum(container_spec_cpu_quota{namespace=\"$namespace\",container=\"$service\"})/100000",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "CPU 负载",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\",container=\"$service\"}[5m]))/sum(container_spec_cpu_quota{namespace=\"$namespace\",pod=\"$pod\",container=\"$service\"})*10000*100"
    }
   ]
  },
  {
   "title": "当前pod可用cpu",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{namespace=\"$namespace\",pod=\"$pod\",container=\"$service\"})/100000-sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\",container=\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "JVM 总线程数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_threads_started_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "JVM 创建线程峰值",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_threads_peak{namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "JVM内线程死锁数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "当前产生线程数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "守护进程线程数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "JVM 内线程死锁监视器数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_threads_deadlocked_monitor{namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, namespace)(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\",container=\"$service\"}[5m]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "新生代 / 年老带GC次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",gc=\"MarkSweepCompact\"}[1m])",
     "legendFormat": "老年代GC次数"
    },
    {
     "expr": "rate(jvm_gc_collection_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",gc=\"Copy\"}[1m])",
     "legendFormat": "新生代GC次数"
    }
   ]
  },
  {
   "title": "新生带GC / 年老带GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{namespace=\"$namespace\",pod=~\"$pod\",gc=\"MarkSweepCompact\"}[1m])",
     "legendFormat": "[{{pod}}] 年老代GC"
    },
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{pod=~\"$pod\",gc=\"Copy\"}[1m])",
     "legendFormat": "[{{pod}}] 新生代GC"
    }
   ]
  },
  {
   "title": "jvm 已用堆内存 / 已用非堆内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=\"$namespace\",pod=~\"$pod\",area=\"heap\"}",
     "legendFormat": "[ {{pod}} ]已用堆内存"
    },
    {
     "expr": "jvm_memory_bytes_used{namespace=\"$namespace\",pod=~\"$pod\",area=\"nonheap\"}",
     "legendFormat": "[ {{pod}} ]已用非堆内存"
    }
   ]
  },
  {
   "title": "jvm 最大内存 / 初始化内存 / 初始化非内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{namespace=\"$namespace\",pod=~\"$pod\",area=\"heap\"}",
     "legendFormat": "最大堆内存 {{pod}} "
    },
    {
     "expr": "jvm_memory_bytes_init{namespace=\"$namespace\",pod=~\"$pod\",area=\"heap\"}",
     "legendFormat": "初始化堆内存 {{pod}} "
    },
    {
     "expr": "jvm_memory_bytes_init{namespace=\"$namespace\",pod=~\"$pod\",area=\"nonheap\"}",
     "legendFormat": "初始化非堆内存 {{pod}} "
    }
   ]
  },
  {
   "title": "活跃线程",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "[{{pod}}]当前活跃线程"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "[{{pod}}]守护进程线程"
    }
   ]
  },
  {
   "title": "JVM 加载类数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "[{{pod}}]"
    }
   ]
  },
  {
   "title": "Memory area [$memarea]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"$memarea\",namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "Upper limit"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "loaded "
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "repeat": "mempool",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Max "
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "GC time increase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  }
 ]
}