{
 "title": "RabbitMQ Dashboard",
 "description": "Rabbitmq stats and alerting using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(rabbitmq_running, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "$node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(rabbitmq_running{node=~\"$node\"})",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "$node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(rabbitmq_running{node=~\"$node\"})",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "$node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(rabbitmq_running{node=~\"$node\"})",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "Disk limit Alarm",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_node_disk_free_alarm{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory limit Alarm",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_node_mem_alarm{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Connections, channels and consumers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rabbitmq_connections)", "legendFormat": "connections" },
    { "expr": "sum(rabbitmq_channels)", "legendFormat": "channels" },
    { "expr": "sum(rabbitmq_queue_consumers)", "legendFormat": "consumers" }
   ]
  },
  {
   "title": "Nodes Up",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_running", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Messages per Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Messages status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rabbitmq_queue_messages_ready) by (queue)",
     "legendFormat": "{{queue}}:ready"
    },
    {
     "expr": "max(rabbitmq_queue_messages_published_total) by (queue)",
     "legendFormat": "{{queue}}:published"
    },
    {
     "expr": "max(rabbitmq_queue_messages_delivered_total) by (queue)",
     "legendFormat": "{{queue}}:delivered"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_unacknowledged)",
     "legendFormat": "{{queue}}:unack"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "min(rabbitmq_node_disk_free{node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}:free"
    },
    {
     "expr": "min(rabbitmq_node_disk_free_limit{node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_node_mem_used{node=~\"$node\"}) by (node) / sum(rabbitmq_node_mem_limit{node=~\"$node\"}) by (node) *100",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}